dist: trusty

language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer

env:
  - PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~3.4.0"

matrix:
  include:
    -
      php: 7.1
      env: PHPUNIT_CONFIG="phpunit.xml" SYMFONY_VERSION="~2.8.0" DEPS="low"
    -
      php: 7.2
      env: RUN_PHPSTAN="yes"

branches:
  only:
    - master
    - /^\d.\d+-release$/

before_script:
  - phpenv config-rm xdebug.ini || true
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  # Install Flex as a global dependency to enable usage of extra.symfony.require
  # while keeping Flex recipes from applying
  - composer global require --no-scripts symfony/flex

  - if [ "$SYMFONY_VERSION" != "" ] ; then composer config extra.symfony.require $SYMFONY_VERSION ; fi

  # PHPStan cannot be installed on Symfony 2.8
  - if [ "$SYMFONY_VERSION" = "~2.8.0" ] ; then composer remove --dev --no-update phpstan/phpstan phpstan/phpstan-phpunit ; fi

  - |
    if [ "$DEPS" = "low" ] ; then
      composer update --no-suggest --prefer-dist --prefer-lowest --prefer-stable
    else
      composer update --no-suggest --prefer-dist
    fi

script:
  - composer validate --strict
  - if [ "$PHPUNIT_CONFIG" != "" ] ; then vendor/bin/phpunit -c $PHPUNIT_CONFIG --colors=always ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan ; fi
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan-tests ; fi

notifications:
  email: false
  slack:
    rooms:
      - secure: "Rg+8sJ+133zAPj5R+asg67yztkrk+Z0IZ/Ul+LvyoQ+RMN72Hay+HEMk+78KmPY0pPrPd1Poz5/THntdv+CkII8bKa8A7Grf+lx/S7M2lC3aazNzU1PZnijtTSgKPBLID2SDtR2INxH0mXsTFyVBI7mbCd1jllVoJyOy9Qf5Qr7TccTkEyjDwWWqi127tKA8VNYNgITo/WbWr/jCvxU5neMLLUGnFQ18fGurJoHjTxYTJkTR3wfNFo4uz4hOg0Sdafsc1vnoZCmNwGjpov4wqkiM82AD+MsbEhWyB5k5/fbxJXJcSUyJPBWspGCUoouwqYjH1kGDGLFtL5C67y5sPYn6nrLKJ+0seJ8SZt34e62lp0uvkfbJoMe2unvThAAvErOnnL0m7fajfUZMzt6K9USs4osEbMOZDsGcUkFgthawCBGXH3ioaqba5m6PH/6SBXZpto5cT2299WnJyEuAaWwZbJHQro8gfqi18zgp10EuPsyF9ZwRJJQv9SLoUUEvxMRIbPTJx2eY8f21bs4C7NjSHxlZ8zbOQWVOvZ6P91PSGYwRLVTnpIoDchQpqsdWMjgcaWDtjCXi1VkmJW/Y+MLsVQEtOeOEYBgAWxjZc4WzbJ04Yso7UqmRtvBM3wkdFcV7N1xlTa2X7NwUr3TWx3+dW+pSmxFow67e4/O2OJ8="
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
