services:
    netgen_block_manager.site_api.item.value_converter.ezlocation:
        class: Netgen\BlockManager\SiteAPI\Item\ValueConverter\LocationValueConverter
        decorates: netgen_block_manager.item.value_converter.ezlocation
        arguments:
            - "@netgen_block_manager.site_api.item.value_converter.ezlocation.inner"
            - "@netgen.ezplatform_site.load_service"

    netgen_block_manager.site_api.item.value_converter.ezcontent:
        class: Netgen\BlockManager\SiteAPI\Item\ValueConverter\ContentValueConverter
        decorates: netgen_block_manager.item.value_converter.ezcontent
        arguments:
            - "@netgen_block_manager.site_api.item.value_converter.ezcontent.inner"
            - "@netgen.ezplatform_site.load_service"

    netgen_block_manager.site_api.item.value_loader.ezlocation:
        class: Netgen\BlockManager\SiteAPI\Item\ValueLoader\LocationValueLoader
        decorates: netgen_block_manager.item.value_loader.ezlocation
        arguments:
            - "@netgen.ezplatform_site.load_service"

    netgen_block_manager.site_api.item.value_loader.ezcontent:
        class: Netgen\BlockManager\SiteAPI\Item\ValueLoader\ContentValueLoader
        decorates: netgen_block_manager.item.value_loader.ezcontent
        arguments:
            - "@netgen.ezplatform_site.load_service"

    netgen_block_manager.site_api.item.value_url_generator.ezlocation:
        class: Netgen\BlockManager\SiteAPI\Item\ValueUrlGenerator\LocationValueUrlGenerator
        decorates: netgen_block_manager.item.value_url_generator.ezlocation
        arguments:
            - "@router"

    netgen_block_manager.site_api.item.value_url_generator.ezcontent:
        class: Netgen\BlockManager\SiteAPI\Item\ValueUrlGenerator\ContentValueUrlGenerator
        decorates: netgen_block_manager.item.value_url_generator.ezcontent
        arguments:
            - "@router"
