view:
    block_view:
        app:
            ibexa_component\override:
                template: "@NetgenLayoutsIbexaSiteApi/app/block/ibexa_component.html.twig"
                match:
                    block\definition: ibexa_component
