view:
    item_view:
        app:
            ezcontent\siteapi:
                template: "@NetgenLayoutsEzPlatformSiteApi/app/item/ezcontent.html.twig"
                match:
                    item\value_type: ezcontent
            ezlocation\siteapi:
                template: "@NetgenLayoutsEzPlatformSiteApi/app/item/ezlocation.html.twig"
                match:
                    item\value_type: ezlocation
