view:
    item_view:
        api:
            ezcontent\siteapi:
                template: "@NetgenSiteAPIBlockManager/api/item/ezcontent.html.twig"
                match:
                    item\value_type: ezcontent
            ezlocation\siteapi:
                template: "@NetgenSiteAPIBlockManager/api/item/ezlocation.html.twig"
                match:
                    item\value_type: ezlocation
