view:
    item_view:
        app:
            ibexa_content\siteapi:
                template: "@NetgenLayoutsIbexaSiteApi/app/item/ibexa_content.html.twig"
                match:
                    item\value_type: ibexa_content
            ibexa_location\siteapi:
                template: "@NetgenLayoutsIbexaSiteApi/app/item/ibexa_location.html.twig"
                match:
                    item\value_type: ibexa_location
